<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="8768" started-at="2016-08-24T04:44:15Z" finished-at="2016-08-24T04:44:24Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="8768" started-at="2016-08-24T04:44:15Z" finished-at="2016-08-24T04:44:24Z">
      <class name="com.yourcompany.SampleSauceReportScript">
        <test-method status="FAIL" signature="main()[pri:0, instance:com.yourcompany.SampleSauceReportScript@4b9e13df]" name="main" duration-ms="8252" started-at="2016-08-23T21:44:15Z" finished-at="2016-08-23T21:44:23Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [I am a page title - Sauce Banana] but found [I am a page title - Sauce Labs]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [I am a page title - Sauce Banana] but found [I am a page title - Sauce Labs]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at com.yourcompany.SampleSauceReportScript.main(SampleSauceReportScript.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- main -->
        <test-method status="PASS" signature="after(org.testng.ITestResult)[pri:0, instance:com.yourcompany.SampleSauceReportScript@4b9e13df]" name="after" is-config="true" duration-ms="471" started-at="2016-08-23T21:44:23Z" finished-at="2016-08-23T21:44:24Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=main status=FAILURE method=SampleSauceReportScript.main()[pri:0, instance:com.yourcompany.SampleSauceReportScript@4b9e13df] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- after -->
      </class> <!-- com.yourcompany.SampleSauceReportScript -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
